# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7982c230d9a17f9a368aa104674585d4bb4ead176d1a960d8e28a0ea873c81123fd3e61602d9b55628374d4431e1aeffc5060af6bcf8e42ca6384d52f89f1c2e

test:
  secret_key_base: ff8d93a3db88683067ab4a21c49e2396c4b97389c7cee682b84690234db872e8d54104e724fd064ab05422837ec41aad4a9da63dcbf22f35b41b29149969c61c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
